confirmonquit: false
git:
  autofetch: true
  merging:
    manualcommit: false
  skiphookprefix: WIP
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never --theme="OneHalfDark"
gui:
  commitlength:
    show: true
  mouseevents: false
  scrollheight: 2
  scrollpastbottom: true
  theme:
    activebordercolor:
    - cyan
    - bold
    inactivebordercolor:
    - white
    lighttheme: false
    optionstextcolor:
    - blue
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
keybinding:
  universal:
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextMatch: '='
    prevMatch: '-'
    new: 'k'
    edit: 'o'
    openFile: 'O'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-k>'
    scrollDownMain-alt2: '<c-j>'
    undo: '<c-z>'
    redo: '<c-r>'
  files:
    ignoreFile: 'I'
  commits:
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    toggleDiffCommit: 'l'
  branches:
    viewGitFlowOptions: 'I'
